name: Compile TWRP
on:
  push:
    branches: [ 'twrp-5.1' ]
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      LC_ALL: "C"
    steps:
      - name: Configure
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/null
          sudo chmod +x /usr/bin/repo
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          sudo apt update
          sudo apt install -yq python2-minimal schedtool build-essential git m4 gcc-multilib g++-multilib
          git config --global user.email "116288337+xunmod@users.noreply.github.com"
          git config --global user.name "xunmod@bot"
          git config --global color.ui false
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Get source
        run: |
          mkdir $GITHUB_WORKSPACE/twrp
          cd $GITHUB_WORKSPACE/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-5.1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)
      - uses: actions/checkout@v5
        with:
          path: 'twrp/device/Xiaoxun'
      - name: Build
        shell: bash
        run: |
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python
          cd $GITHUB_WORKSPACE/twrp/device/Xiaoxun
          export dt_commit=$(git rev-parse --short HEAD)
          cd $GITHUB_WORKSPACE/twrp
          patch -p1 < device/Xiaoxun/fix_build.patch
          source build/envsetup.sh
          lunch omni_sl8521e_1h10ll_sw761-eng
          mka -j$(nproc --all) recoveryimage
          export twrp_version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
          cp out/target/product/sl8521e_1h10ll_sw761/recovery.img ../twrp-${twrp_version}_${dt_commit}-sl8521e_1h10ll_sw761.img
          mkdir ../signutils
          cp $(find out/host -name sprd_sign) $(find out/host -name imgheaderinsert) ../signutils/
          #lunch omni_sl8521e_1h10ll_sw763-eng
          #mka -j$(nproc --all) recoveryimage
          #cp out/target/product/sl8521e_1h10ll_sw763/recovery.img ../twrp-${twrp_version}_${dt_commit}-sl8521e_1h10ll_sw763.img
          #lunch omni_sl8521e_1h10ll_sw771-eng
          #mka -j$(nproc --all) recoveryimage
          #cp out/target/product/sl8521e_1h10ll_sw771/recovery.img ../twrp-${twrp_version}_${dt_commit}-sl8521e_1h10ll_sw771.img
      - uses: actions/upload-artifact@v5
        with:
          name: TWRP Image for MiKidsWatch 4
          path: 'twrp-*_sw761.img'
      - uses: actions/upload-artifact@v5
        with:
          name: sign utils
          path: 'signutils'
      #- uses: actions/upload-artifact@v5
      #  with:
      #    name: TWRP Image for MiKidsWatch 4x
      #    path: 'twrp-*_sw763.img'
      #- uses: actions/upload-artifact@v5
      #  with:
      #    name: TWRP Image for MiKidsWatch 6x
      #    path: 'twrp-*_sw771.img'
